services:
  my-fastapi-app:
    build: 
      context: ./backend  # Build the image from the current directory (.)
      args: 
        - --no-cache=True
    volumes:
      - ./backend:/app  # Mount current directory to /app in the container
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    depends_on:
      - mysql  # Wait for MySQL to start before running the FastAPI app
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'mysql'
      #    We cannot set user as 'root' if mysql is below version of 5.x: https://github.com/docker-library/mysql/issues/129
      #    MYSQL_USER: 'root'
      #    MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata: