services:
  svelte-app:
    image: todocards/svelte-app
    ports:
      - "80:80"  # Map container port to default web server
    depends_on:
      - flask-app  # Wait for backend to start before running the Flask app
  flask-app:
    image: todocards/flask-app
    ports:
      - "5000:5000"  # Flask uses port 5000 as default
    depends_on:
      - mysql  # Wait for MySQL to start before running the FastAPI app
  mysql:
    image: todocards/mysql
    ports:
      - "3306:3306"